version: '3.7'
services:
    oidc-provider:
        container_name: oidc-provider
        networks:
            nav.docker-internal:
                aliases:
                    - oidc-provider.nav.docker-internal
        image: 'navikt/stub-oidc-provider:latest'
        ports:
            - '9000:9000'
        environment:
            PORT: '9000'
            CALLBACK_URL: 'http://localhost:5000/callback'
            ISSUER: 'https://localhost:9000'

    oidc-provider-gui:
        container_name: oidc-provider-gui
        networks:
            nav.docker-internal:
                aliases:
                    - oidc-provider-gui.nav.docker-internal
        image: 'navikt/pb-oidc-provider-gui:latest'
        ports:
            - '5000:5000'
        depends_on:
            - oidc-provider
        environment:
            REDIRECT_URL: 'http://localhost:8088/dekoratoren'
            AUTO_REDIRECT_TO_FRONTEND: 'true'

    mocks:
        container_name: mocks
        networks:
            nav.docker-internal:
                aliases:
                    - mocks.nav.docker-internal
        image: 'navikt/pb-nav-mocked:latest'
        ports:
            - '8200:8080'
        environment:
            CORS_ALLOWED_ORIGINS: 'localhost:8088'
            OIDC_ISSUER: 'https://localhost:9000'
            OIDC_ACCEPTED_AUDIENCE: 'stubOidcClient'
            OIDC_JWKS_URI: 'http://oidc-provider.nav.docker-internal:9000/certs'
        depends_on:
            - oidc-provider

#  dekoratoren:
#    container_name: dekoratoren
#    networks:
#      nav.docker-internal:
#        aliases:
#          - dekoratoren.nav.docker-internal
#    image: "navikt/nav-dekoratoren:latest"
#    build: .
#    ports:
#      - "8088:8088"
#    environment:
#      BASE_URL: 'http://localhost:8088'
#      BASE_URL_APP: "http://localhost:8088/dekoratoren"
#      BASE_URL_ENONIC: 'https://www-q1.nav.no'
#      API_INNLOGGINGSLINJE_URL: 'http://localhost:8200/innloggingslinje-api/auth'
#      API_VARSELINNBOKS_URL: 'https://www-q0.nav.no/person/varselinnboks'
#      BACKEND_MENY_URL: 'http://localhost:8088/dekoratoren/api/meny'
#      BACKEND_SOK_URL: 'http://localhost:8088/dekoratoren/api/sok'
#      MINSIDE_ARBEIDSGIVER_URL: 'https://arbeidsgiver-q.nav.no/min-side-arbeidsgiver/'
#      LOGOUT_URL: 'http://localhost:5000/?logout'
#      LOGIN_URL: 'http://localhost:5000'

networks:
    nav.docker-internal:
