---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-dekoratoren
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  port: 8088
  liveness:
    path: /dekoratoren/isAlive
    initialDelay: 10
  readiness:
    path: /dekoratoren/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /dekoratoren/metrics
  replicas:
    min: 2
    max: 8
  #ingresses
  #accessPolicy
  #env
  envFrom:
    - secret: nav-dekoratoren
  resources:
    limits:
      cpu: '3'
      memory: 1500Mi
    requests:
      cpu: 500m
      memory: 500Mi
