---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-dekoratoren
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{image}}:{{version}}
  port: 8088
  liveness:
    path: /gcp-dekoratoren/isAlive
    initialDelay: 10
  readiness:
    path: /gcp-dekoratoren/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /gcp-dekoratoren/metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - https://www.nav.no/gcp-dekoratoren
  accessPolicy:
    outbound:
      external:
        - host: www.nav.no
        - host: innloggingslinje-api.nav.no
  env:
    - name: ENV
      value: prod
    - name: XP_BASE_URL
      value: https://www.nav.no
    - name: APP_BASE_URL
      value: https://www.nav.no
    - name: APP_BASE_PATH
      value: /gcp-dekoratoren
    - name: API_XP_SERVICES_URL
      value: https://www.nav.no/_/service
    - name: API_VARSELINNBOKS_URL
      value: https://www.nav.no/person/varselinnboks
    - name: API_INNLOGGINGSLINJE_URL
      value: https://www.nav.no/person/innloggingsstatus
    - name: API_UNLEASH_PROXY_URL
      value: https://www.nav.no/person/pb-unleash-proxy
    - name: MINSIDE_ARBEIDSGIVER_URL
      value: https://arbeidsgiver.nav.no/min-side-arbeidsgiver/
    - name: DITT_NAV_URL
      value: https://www.nav.no/person/dittnav/
    - name: LOGIN_URL
      value: https://loginservice.nav.no
    - name: LOGOUT_URL
      value: https://loginservice.nav.no/slo
    - name: FEEDBACK_API_URL
      value: https://dekoratoren-api.nav.no/event
  resources:
    limits:
      cpu: '3'
      memory: 1500Mi
    requests:
      memory: 1500Mi
