---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: nav-dekoratoren
    namespace: {{namespace}}
    labels:
      team: {{team}}
spec:
    image: navikt/{{reponame}}:{{version}}
    port: 8088
    liveness:
        path: /dekoratoren/isalive
        initialDelay: 10
    readiness:
        path: /dekoratoren/isready
        initialDelay: 10
    prometheus:
        path: /metrics
    replicas:
        min: 2
        max: 4
    ingresses:
        - https://dekoratoren.nais.oera.no
        - https://www.nav.no/dekoratoren
    env:
        - name: NAV_BASE_URL
          value: https://www.nav.no
        - name: APP_BASE_URL
          value: https://www.nav.no/dekoratoren
        - name: API_ENONIC_MENY_URL
          value: https://www.nav.no/_/service/no.nav.navno/menu
        - name: API_ENONIC_SOK_URL
          value: https://www.nav.no/_/service/navno.nav.no.search/search2
        - name: API_VARSELINNBOKS_URL
          value: https://www.nav.no/person/varselinnboks
        - name: API_INNLOGGINGSLINJE_URL
          value: https://www.nav.no/innloggingslinje-api/auth
        - name: PAGE_MINSIDE_ARBEIDSGIVER_URL
          value: https://arbeidsgiver.nav.no/min-side-arbeidsgiver/
        - name: PAGE_DITT_NAV_URL
          value: https://www.nav.no/person/dittnav/
        - name: LOGIN_URL
          value: https://loginservice.nav.no
        - name: LOGOUT_URL
          value: https://loginservice.nav.no/slo
    resources:
        limits:
            cpu: '3'
            memory: 768Mi
        requests:
            cpu: 200m
            memory: 512Mi
