---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: nav-dekoratoren
    namespace: {{namespace}}
    labels:
        team: personbruker
spec:
    image: {{image}}:{{version}}
    port: 8088
    liveness:
        path: /isAlive
        initialDelay: 10
    readiness:
        path: /isReady
        initialDelay: 10
    prometheus:
        enabled: true
        path: /metrics
    replicas:
        min: 2
        max: 4
    ingresses:
        - https://dekoratoren.dev.nav.no
    accessPolicy:
        outbound:
            external:
                - host: innloggingslinje-api.dev.nav.no
                - host: www-q1.nav.no
    env:
        - name: XP_BASE_URL
          value: https://www-q1.nav.no
        - name: APP_BASE_URL
          value: https://dekoratoren.dev.nav.no
        - name: API_XP_SERVICES_URL
          value: https://www-q1.nav.no/_/service
        - name: API_VARSELINNBOKS_URL
          value: https://www-q1.nav.no/person/varselinnboks
        - name: API_INNLOGGINGSLINJE_URL
          value: https://innloggingslinje-api.dev.nav.no/auth
        - name: API_UNLEASH_PROXY_URL
          value: https://www-q1.nav.no/person/pb-unleash-proxy
        - name: MINSIDE_ARBEIDSGIVER_URL
          value: https://arbeidsgiver-q1.nav.no/min-side-arbeidsgiver/
        - name: DITT_NAV_URL
          value: https://www-q1.nav.no/person/dittnav/
        - name: LOGIN_URL
          value: https://loginservice.dev.nav.no
        - name: LOGOUT_URL
          value: https://loginservice.dev.nav.no/slo
        - name: FEEDBACK_API_URL
          value: https://dekoratoren-api.dev-gcp.nais.io/event/
    resources:
        limits:
            cpu: '3'
            memory: 1500Mi
        requests:
            memory: 1500Mi
