---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: nav-dekoratoren
    namespace: {{namespace}}
    labels:
        team: personbruker
spec:
    image: {{image}}:{{version}}
    port: 8088
    liveness:
        path: /dekoratoren/isAlive
        initialDelay: 10
    readiness:
        path: /dekoratoren/isReady
        initialDelay: 10
    prometheus:
        enabled: true
        path: /dekoratoren/metrics
    replicas:
        min: 2
        max: 4
    ingresses:
        - https://dekoratoren-q0.nais.oera-q.local
        - https://appres-q0.nav.no/common-html/v4/navno
        - https://www-q0.nav.no/dekoratoren
    env:
        - name: XP_BASE_URL
          value: https://www-q0.nav.no
        - name: APP_BASE_URL
          value: https://www-q0.nav.no
        - name: APP_BASE_PATH
          value: /dekoratoren
        - name: API_XP_SERVICES_URL
          value: https://www-q0.nav.no/_/service
        - name: API_VARSELINNBOKS_URL
          value: https://www.dev.nav.no/person/varselinnboks
        - name: API_INNLOGGINGSLINJE_URL
          value: https://innloggingsstatus.dev.nav.no/person/innloggingsstatus
        - name: API_UNLEASH_PROXY_URL
          value: https://www.dev.nav.no/person/pb-unleash-proxy
        - name: MINSIDE_ARBEIDSGIVER_URL
          value: https://arbeidsgiver-q0.nav.no/min-side-arbeidsgiver/
        - name: DITT_NAV_URL
          value: https://www-q0.nav.no/person/dittnav/
        - name: LOGIN_URL
          value: https://loginservice-q.nav.no
        - name: LOGOUT_URL
          value: https://loginservice-q.nav.no/slo
        - name: FEEDBACK_API_URL
          value: https://dekoratoren-api.dev-gcp.nais.io/event
    resources:
        limits:
            cpu: '3'
            memory: 1500Mi
        requests:
            memory: 1500Mi
