---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: nav-dekoratoren
    namespace: {{namespace}}
    labels:
        team: {{team}}
spec:
    image: navikt/{{reponame}}:{{version}}
    port: 8088
    liveness:
        path: /dekoratoren/isalive
        initialDelay: 10
    readiness:
        path: /dekoratoren/isready
        initialDelay: 10
    prometheus:
        path: /metrics
    replicas:
        min: 2
        max: 4
    ingresses:
        - https://dekoratoren-q0.nais.oera-q.local/
        - https://www-q0.nav.no/dekoratoren
    env:
        - name: XP_BASE_URL
          value: https://www-q1.nav.no
        - name: APP_BASE_URL
          value: https://www-q0.nav.no/dekoratoren
        - name: API_XP_MENY_URL
          value: https://www-q1.nav.no/_/service/no.nav.navno/menu
        - name: API_XP_SOK_URL
          value: https://www-q1.nav.no/_/service/navno.nav.no.search/search2/sok
        - name: API_VARSELINNBOKS_URL
          value: https://www-q0.nav.no/person/varselinnboks
        - name: API_INNLOGGINGSLINJE_URL
          value: https://www-q0.nav.no/innloggingslinje-api/auth
        - name: MINSIDE_ARBEIDSGIVER_URL
          value: https://arbeidsgiver-q.nav.no/min-side-arbeidsgiver/
        - name: DITT_NAV_URL
          value: https://www-q0.nav.no/person/dittnav/
        - name: LOGIN_URL
          value: https://loginservice-q.nav.no
        - name: LOGOUT_URL
          value: https://loginservice-q.nav.no/slo
    resources:
        limits:
            cpu: '3'
            memory: 768Mi
        requests:
            cpu: 200m
            memory: 512Mi
