name: Deploy to prod
on:
  release:
    types: [released]

jobs:
  deploy:
    if: github.event.release.target_commitish == 'master'
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      NAIS_RESOURCE: .nais/prod.yaml
      IMAGE_NAME: release-${{ github.ref_name }}
      CLUSTER: prod-gcp
      BUILD_MODE: prod
    secrets: inherit
