name: Deploy-to-beta
on:
  workflow_dispatch:
    inputs:
      build_mode:
        type: choice
        required: true
        description: 'Build-time NODE_ENV'
        default: 'prod'
        options:
          - prod
          - dev

jobs:
  deploy:
    uses: ./.github/workflows/deploy.dev.shared.yml@${GITHUB_SHA}
    with:
      username: .nais/dev-gcp/personbruker.yaml
    secrets: inherit
